---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox è un copilota Infrastructure as Code (IaC) che aiuta gli sviluppatori e i DevOps a generare il codice necessario per eseguire qualsiasi operazione supportata da NetApp Workload Factory.' 
---
= Ulteriori informazioni sull'automazione dei codebox
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox è un copilota Infrastructure as Code (IaC) che aiuta gli sviluppatori e i DevOps a generare il codice necessario per eseguire qualsiasi operazione supportata da NetApp Workload Factory.  Codebox è allineato con le modalità operative di Workload Factory (_base_, _sola lettura_ e _lettura/scrittura_) e definisce un percorso chiaro per la prontezza all'esecuzione, oltre a fornire un catalogo di automazione per un rapido riutilizzo futuro.



== Funzionalità Codebox

Codebox offre due funzionalità IAC principali:

* _Codebox Viewer_ mostra il file IAC generato da una specifica operazione di flusso di lavoro mediante la corrispondenza di voci e selezioni dalla procedura guidata grafica o dall'interfaccia di conversazione testuale. Anche se Codebox Viewer supporta la codifica a colori per semplificare la navigazione e l'analisi, non consente la modifica, ma solo la copia o il salvataggio del codice nel catalogo di automazione.
* _Codebox Automation Catalog_ mostra tutti i job IAC salvati, consentendo di utilizzarli facilmente per un utilizzo futuro. I lavori del catalogo di automazione vengono salvati come modelli e visualizzati nel contesto delle risorse ad essi applicabili.


Inoltre, quando si impostano le credenziali di Workload Factory, Codebox visualizza dinamicamente le autorizzazioni AWS necessarie per creare policy IAM.  Le autorizzazioni vengono fornite per ogni funzionalità di Workload Factory che si intende utilizzare (database, AI, FSx per ONTAP e così via) e sono personalizzate in base al fatto che gli utenti della policy riceveranno autorizzazioni di _sola lettura_ o autorizzazioni di _lettura/scrittura_ complete.  Basta copiare le autorizzazioni da Codebox e incollarle nella AWS Management Console, in modo che Workload Factory disponga delle autorizzazioni corrette per gestire i carichi di lavoro.



== Formati di codice supportati

I formati di codice supportati includono:

* API REST di Workload Factory
* CLI AWS
* CloudFormation AWS




== Informazioni correlate

link:use-codebox.html["Informazioni sull'utilizzo di Codebox"].

link:https://console.workloads.netapp.com/api-doc["Documentazione dell'API REST di Workload Factory"^] .
