---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 'È possibile configurare NetApp Workload Factory per inviare notifiche a una persona o a un"altra applicazione quando si verificano determinati tipi di eventi.' 
---
= Configurare le notifiche di NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
È possibile configurare il servizio di notifica NetApp Workload Factory per inviare notifiche come avvisi nella console NetApp o a un argomento Amazon SNS.  Le notifiche inviate come avvisi vengono visualizzate nella console NetApp quando è distribuito un agente o un collegamento della console.  Quando Workload Factory pubblica notifiche su un argomento Amazon SNS, gli abbonati all'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche negli endpoint configurati per l'argomento (ad esempio messaggi e-mail o SMS).



== Tipi di notifica e messaggi

Workload Factory invia notifiche per i seguenti eventi:

[cols="6*"]
|===
| Evento | Descrizione | Tipo di notifica | Severità | Carico di lavoro | Tipo di risorsa 


| Alcune istanze del database nel tuo account non sono ben progettate | Tutte le istanze di Microsoft SQL Server nel tuo account sono state analizzate per individuare eventuali problemi ben progettati.  La descrizione di questo evento fornisce il numero di istanze ben progettate e di istanze non ottimizzate.  Esaminare i risultati e le raccomandazioni sullo stato ben progettati nell'inventario dei database dalla console Workload Factory. | Ben progettato | Consiglio | Database | Istanza di Microsoft SQL Server 


| Distribuzione del server Microsoft SQL Server/PostgreSQL riuscita | L'implementazione dell'host Microsoft SQL Server o PostgreSQL è riuscita. Per ulteriori informazioni, consultare il monitoraggio dei job. | Implementazione | Successo | Database | FSx per ONTAP, host DB 


| Distribuzione del server Microsoft SQL Server/PostgreSQL non riuscita | L'implementazione dell'host Microsoft SQL Server o PostgreSQL non è riuscita. Per ulteriori informazioni, consultare il monitoraggio dei job. | Implementazione | Errore | Database | FSx per ONTAP, host DB 


| Creazione della relazione di replicazione non riuscita | La creazione di una relazione di replica SnapMirror non è riuscita.  Per maggiori informazioni, visita Tracker. | Replicazione | Critico | Deposito generale | FSx per ONTAP 


| Errore nella creazione di FSx per ONTAP | Il processo di creazione del file system FSx for ONTAP non è riuscito.  Per maggiori informazioni, visita Tracker. | FSx per l'azione del file system ONTAP | Critico | Deposito generale | FSx per ONTAP 


| Rilevato problema FSx per ONTAP | Tutti i file system FSx per ONTAP sono stati analizzati per individuare eventuali problemi di architettura corretta.  La scansione ha rilevato uno o più problemi.  Per ulteriori informazioni, consultare l'analisi ben progettata nella dashboard Storage nella console Workload Factory. | Analisi ben progettata | Consiglio | Deposito generale | FSx per file system ONTAP 
|===


== Configurare le notifiche di Workload Factory

Configurare le notifiche di Workload Factory utilizzando la console NetApp o la console Workload Factory.  Se utilizzi la console NetApp , puoi configurare Workload Factory per inviare notifiche come avvisi nella console NetApp o a un argomento Amazon SNS.  È possibile configurare le notifiche dalle *Impostazioni notifiche* nella console NetApp .

.Prima di iniziare
* È necessario configurare Amazon SNS e creare argomenti Amazon SNS tramite la console Amazon SNS o AWS CLI.
* Si noti che Workload Factory supporta il tipo di argomento *Standard*.  Questo tipo di argomento non garantisce che le notifiche vengano inviate agli abbonati nell'ordine in cui sono state ricevute, quindi tienilo in considerazione se hai notifiche critiche o di emergenza.


[role="tabbed-block"]
====
.Configurare le notifiche dalla console NetApp
--
.Fasi
. Accedi allink:https://console.netapp.com["Console NetApp"^] .
. Dal menu della console NetApp , selezionare *Carichi di lavoro*, *Amministrazione* e quindi *Impostazione notifiche*.
. Nella pagina di configurazione delle notifiche, procedi come segue:
+
.. Facoltativo: seleziona *Abilita notifiche NetApp Console* per configurare Workload Factory in modo che invii notifiche nella NetApp Console.
.. Seleziona *Abilita notifiche SNS*.
.. Segui le istruzioni per configurare Amazon SNS dalla console di Amazon SNS.
+
Dopo aver creato l'argomento, copia l'ARN dell'argomento e inseriscilo nel campo *ARN argomento SNS* nella pagina *Impostazione notifiche*.



. Dopo aver verificato la configurazione inviando una notifica di prova, seleziona *Applica*.


.Risultato
Workload Factory è configurato per inviare notifiche all'argomento Amazon SNS specificato.

--
.Configurare le notifiche dalla console Workload Factory
--
.Fasi
. Accedi allink:https://console.workloads.netapp.com["Console Workload Factory"^] .
. Dal menu della console Workload Factory, seleziona *Carichi di lavoro*, *Amministrazione* e quindi *Impostazione notifiche*.
. Seleziona *Abilita notifiche SNS*.
. Segui le istruzioni per configurare Amazon SNS dalla console di Amazon SNS.
. Dopo aver verificato la configurazione inviando una notifica di prova, seleziona *Applica*.


.Risultato
Workload Factory è configurato per inviare notifiche all'argomento Amazon SNS specificato.

--
====


== Iscriviti all'argomento Amazon SNS

Dopo aver configurato Workload Factory per inviare notifiche a un argomento, seguire le istruzioni https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["istruzioni"] nella documentazione di Amazon SNS per iscriverti all'argomento in modo da poter ricevere notifiche da Workload Factory.



== Filtra le notifiche

È possibile ridurre il traffico di notifiche non necessario e indirizzare tipi di notifiche specifici a utenti specifici applicando filtri alle notifiche.  È possibile farlo utilizzando una policy Amazon SNS per le notifiche SNS e le impostazioni delle notifiche nella console NetApp .



=== Filtra le notifiche di Amazon SNS

Quando ti iscrivi a un argomento Amazon SNS, per impostazione predefinita ricevi tutte le notifiche pubblicate su quell'argomento.  Se desideri ricevere solo notifiche specifiche dall'argomento, puoi utilizzare un criterio di filtro per controllare quali notifiche ricevere.  I criteri di filtro fanno sì che Amazon SNS invii all'abbonato solo le notifiche che corrispondono al criterio di filtro.

Puoi filtrare le notifiche di Amazon SNS in base ai seguenti criteri:

[cols="3*"]
|===
| Descrizione | Nome del campo del criterio di filtro | Valori possibili 


| Tipo di risorsa | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Carico di lavoro | `workload` | `WLMDB` 


| Priorità | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Tipo di notifica | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Fasi
. Nella console Amazon SNS, modifica i dettagli dell'abbonamento per l'argomento SNS.
. Nell'area *Criteri di filtro abbonamento*, seleziona per filtrare in base agli *Attributi del messaggio*.
. Abilitare l'opzione *Criterio filtro abbonamento*.
. Immettere un criterio di filtro JSON nella casella *Editor JSON*.
+
Ad esempio, il seguente criterio di filtro JSON accetta notifiche dalla risorsa Microsoft SQL Server correlate al carico di lavoro WLMDB, hanno una priorità di Successo o Errore e forniscono dettagli sullo stato Well-architected:

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Seleziona *Salva modifiche*.


Per altri esempi di criteri di filtro, fare riferimento a https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Criteri di filtro di esempio di Amazon SNS"^] .

Per ulteriori informazioni sulla creazione di criteri di filtro, fare riferimento a https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Documentazione Amazon SNS"^] .



=== Filtra le notifiche nella console NetApp

È possibile utilizzare le impostazioni delle notifiche della console NetApp per filtrare le notifiche ricevute nella console in base al livello di gravità, ad esempio Critico, Informazioni o Avviso.

Per ulteriori informazioni sul filtraggio delle notifiche nella Console, fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["Documentazione della console NetApp"^] .
