---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 'È possibile configurare BlueXP Workload Factory per inviare notifiche a una persona o a un"altra applicazione quando si verificano determinati tipi di eventi.' 
---
= Configurare le notifiche di fabbrica del carico di lavoro BlueXP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
È possibile configurare il servizio di notifica della Workload Factory di BlueXP per inviare notifiche al servizio di avvisi BlueXP o a un argomento Amazon SNS. Le notifiche inviate agli avvisi BlueXP vengono visualizzate nel pannello degli avvisi BlueXP. Quando la Workload Factory pubblica notifiche su un argomento Amazon SNS, i sottoscrittori dell'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche sugli endpoint configurati per l'argomento (ad esempio, tramite e-mail o SMS).



== Tipi di notifica e messaggi

Workload Factory invia notifiche per i seguenti eventi:

[cols="6*"]
|===
| Evento | Descrizione | Tipo di notifica | Severità | Carico di lavoro | Tipo di risorsa 


| Alcune istanze del database nel tuo account non sono ben progettate | Tutte le istanze di Microsoft SQL Server nel tuo account sono state analizzate per problemi di architettura corretta. La descrizione di questo evento indica il numero di istanze di architettura corretta e non ottimizzate. Esamina i risultati e le raccomandazioni relative allo stato di architettura corretta nell'inventario dei database dalla console della Workload Factory. | Ben progettato | Consiglio | Database | Istanza di Microsoft SQL Server 


| Distribuzione del server Microsoft SQL Server/PostgreSQL riuscita | L'implementazione dell'host Microsoft SQL Server o PostgreSQL è riuscita. Per ulteriori informazioni, consultare il monitoraggio dei job. | Implementazione | Successo | Database | FSx per ONTAP, host DB 


| Distribuzione del server Microsoft SQL Server/PostgreSQL non riuscita | L'implementazione dell'host Microsoft SQL Server o PostgreSQL non è riuscita. Per ulteriori informazioni, consultare il monitoraggio dei job. | Implementazione | Errore | Database | FSx per ONTAP, host DB 


| Creazione della relazione di replicazione non riuscita | La creazione di una relazione di replica SnapMirror non è riuscita.  Per maggiori informazioni, visita Tracker. | Replicazione | Critico | Deposito generale | FSx per ONTAP 


| Errore nella creazione di FSx per ONTAP | Il processo di creazione del file system FSx for ONTAP non è riuscito.  Per maggiori informazioni, visita Tracker. | FSx per l'azione del file system ONTAP | Critico | Deposito generale | FSx per ONTAP 
|===


== Configurare le notifiche di Workload Factory

Configura le notifiche di Workload Factory tramite la console BlueXP o la console di Workload Factory. Se utilizzi la console BlueXP, puoi configurare Workload Factory per inviare notifiche agli avvisi BlueXP o a un argomento Amazon SNS. Puoi configurare gli avvisi BlueXP dall'area *Impostazioni avvisi e notifiche* di BlueXP.

.Prima di iniziare
* È necessario configurare Amazon SNS e creare argomenti Amazon SNS tramite la console Amazon SNS o AWS CLI.
* Si noti che Workload Factory supporta il tipo di argomento *Standard*. Questo tipo di argomento non garantisce che le notifiche vengano inviate agli abbonati nell'ordine in cui sono state ricevute, quindi è consigliabile tenerlo in considerazione in caso di notifiche critiche o di emergenza.


[role="tabbed-block"]
====
.Configurare le notifiche dalla console BlueXP
--
.Fasi
. Accedere a link:https://console.bluexp.netapp.com["Console BlueXP"^].
. Selezionare *carichi di lavoro* dal menu di navigazione a sinistra.
. Selezionare *Home* per visualizzare tutti i carichi di lavoro o selezionare un carico di lavoro come *archiviazione* o *database*.
. Dalla barra dei menu di Workload Factory, selezionare il menu di configurazione.
. Nel menu, seleziona *Configurazione notifiche Workload Factory*.
. Facoltativo: seleziona *Abilita notifiche BlueXP* per configurare Workload Factory in modo che invii notifiche agli avvisi BlueXP.
. Seleziona *Abilita notifiche SNS*.
. Segui le istruzioni per configurare Amazon SNS dalla console di Amazon SNS.
+
Dopo aver creato l'argomento, copia l'ARN dell'argomento e inseriscilo nel campo *ARN argomento SNS* nella finestra di dialogo *Impostazione notifiche*.

. Dopo aver verificato la configurazione inviando una notifica di prova, seleziona *Applica*.


.Risultato
La fabbrica dei carichi di lavoro è configurata per inviare notifiche all'argomento Amazon SNS specificato.

--
.Configurare le notifiche dalla console di Workload Factory
--
.Fasi
. Accedere a link:https://console.workloads.netapp.com["console di fabbrica del carico di lavoro"^].
. Aprire il menu dell'account dalla barra di navigazione in alto.
. Nel menu, seleziona *Impostazione notifiche*.
. Seleziona *Abilita notifiche SNS*.
. Segui le istruzioni per configurare Amazon SNS dalla console di Amazon SNS.
. Dopo aver verificato la configurazione inviando una notifica di prova, seleziona *Applica*.


.Risultato
La fabbrica dei carichi di lavoro è configurata per inviare notifiche all'argomento Amazon SNS specificato.

--
====


== Iscriviti all'argomento Amazon SNS

Dopo aver configurato la fabbrica del carico di lavoro per inviare notifiche a un argomento, seguire le istruzioni  https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["istruzioni"] nella documentazione di Amazon SNS per iscriverti all'argomento in modo da poter ricevere notifiche da Workload Factory.



== Filtra le notifiche

È possibile ridurre il traffico di notifiche non necessario e indirizzare tipi di notifiche specifici a utenti specifici applicando filtri alle notifiche. È possibile farlo utilizzando una policy Amazon SNS per le notifiche SNS e le impostazioni di notifica BlueXP per le notifiche BlueXP.



=== Filtra le notifiche di Amazon SNS

Quando ti iscrivi a un argomento Amazon SNS, per impostazione predefinita ricevi tutte le notifiche pubblicate su quell'argomento.  Se desideri ricevere solo notifiche specifiche dall'argomento, puoi utilizzare un criterio di filtro per controllare quali notifiche ricevere.  I criteri di filtro fanno sì che Amazon SNS invii all'abbonato solo le notifiche che corrispondono al criterio di filtro.

Puoi filtrare le notifiche di Amazon SNS in base ai seguenti criteri:

[cols="3*"]
|===
| Descrizione | Nome del campo del criterio di filtro | Valori possibili 


| Tipo di risorsa | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Carico di lavoro | `workload` | `WLMDB` 


| Priorità | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Tipo di notifica | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Fasi
. Nella console Amazon SNS, modifica i dettagli dell'abbonamento per l'argomento SNS.
. Nell'area *Criteri di filtro abbonamento*, seleziona per filtrare in base agli *Attributi del messaggio*.
. Abilitare l'opzione *Criterio filtro abbonamento*.
. Immettere un criterio di filtro JSON nella casella *Editor JSON*.
+
Ad esempio, il seguente criterio di filtro JSON accetta notifiche dalla risorsa Microsoft SQL Server correlate al carico di lavoro WLMDB, hanno una priorità di Successo o Errore e forniscono dettagli sullo stato Well-architected:

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Seleziona *Salva modifiche*.


Per altri esempi di criteri di filtro, fare riferimento a https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Criteri di filtro di esempio di Amazon SNS"^] .

Per ulteriori informazioni sulla creazione di criteri di filtro, fare riferimento a https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Documentazione Amazon SNS"^] .



=== Filtra le notifiche BlueXP

Puoi utilizzare le impostazioni di avvisi e notifiche di BlueXP per filtrare gli avvisi e le notifiche ricevuti in BlueXP in base al livello di gravità, ad esempio Critico, Info o Avviso.

Per ulteriori informazioni sul filtraggio delle notifiche in BlueXP, fare riferimento a  https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#filter-notifications["Documentazione BlueXP"^] .
