---
sidebar: sidebar 
permalink: console-experiences.html 
keywords: console, consoles, access, saas, Workload Factory, bluexp, NetApp Workload Factory, NetApp Console 
summary: NetApp Workload Factory è accessibile tramite due console basate sul Web. 
---
= Esperienze di console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory è accessibile tramite due console basate sul Web.  Scopri come accedere a Workload Factory utilizzando la console Workload Factory e la console NetApp .

* * Console NetApp *: offre un'esperienza ibrida in cui puoi gestire i file system FSx for ONTAP e i carichi di lavoro in esecuzione su Amazon FSx for NetApp ONTAP nello stesso posto.
* *Console Workload Factory*: offre un'esperienza Workload Factory dedicata, focalizzata sui carichi di lavoro in esecuzione su Amazon FSx for NetApp ONTAP.




== Accedi a Workload Factory nella console NetApp

È possibile accedere a Workload Factory dalla console NetApp .  Oltre a utilizzare Workload Factory per le funzionalità di archiviazione e carico di lavoro di AWS, puoi anche accedere ad altri servizi dati come NetApp Copy and Sync, NetApp Digital Wallet e altro ancora.

.Fasi
. Accedi allink:https://console.netapp.com["Console NetApp"^] .
. Dal menu NetApp Console, seleziona *Carichi di lavoro* e poi *Panoramica*.




== Accedi a Workload Factory nella console Workload Factory

È possibile accedere a Workload Factory dalla console Workload Factory.

.Fase
. Accedi allink:https://console.workloads.netapp.com["Console Workload Factory"^] .

