---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: 'Workload Factory analizza le configurazioni dei carichi di lavoro per verificarne affidabilità, sicurezza, eccellenza operativa, ottimizzazione dei costi ed efficienza delle prestazioni, fornendo informazioni e consigli per aiutarti a raggiungere l"eccellenza operativa.' 
---
= Crea e gestisci carichi di lavoro ben strutturati con NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory, la suite di gestione NetApp per Amazon FSx for NetApp ONTAP, ti aiuta a mantenere e gestire configurazioni di carichi di lavoro affidabili, sicure, efficienti e convenienti, in linea con l'AWS Well-Architected Framework. Workload Factory fornisce analisi giornaliere dei tuoi carichi di lavoro, raccomandazioni e correzioni automatiche per promuovere operazioni sane dei carichi di lavoro. Automatizzando questo processo, Workload Factory riduce al minimo gli errori umani e garantisce coerenza nella gestione dei carichi di lavoro.



== Come funziona

Workload Factory analizza quotidianamente i carichi di lavoro in esecuzione sulle implementazioni dei file system Amazon FSx for NetApp ONTAP. L'analisi fornisce stato ben architettato, approfondimenti e raccomandazioni.

Una volta completata l'analisi giornaliera, le configurazioni vengono visualizzate come "ottimizzate" o "non ottimizzate" nella dashboard Well-architected per la distribuzione. Troverai il punteggio di ottimizzazione totale, i problemi di configurazione per categoria e un elenco di problemi di configurazione e raccomandazioni. È possibile rivedere i consigli per i problemi di configurazione. Alcuni problemi possono essere risolti automaticamente da Workload Factory, mentre altri richiedono un intervento manuale. In questo caso, Workload Factory fornisce istruzioni dettagliate per aiutarti a implementare le modifiche consigliate.

È possibile ignorare l'analisi delle configurazioni che non si applicano ai propri ambienti. In questo modo si evitano avvisi non necessari e risultati di ottimizzazione imprecisi. Quando si ignora un'analisi di configurazione specifica, Workload Factory non include la configurazione nel punteggio di ottimizzazione totale.



== Perché è importante

Workload Factory applica le best practice ad ambienti di storage, database e VMware di grandi dimensioni, combinando valutazioni continue con suggerimenti e interventi correttivi. Le correzioni automatiche applicate nella console di Workload Factory riducono gli errori umani, garantiscono una gestione uniforme e preservano prestazioni e affidabilità nelle infrastrutture di workload.



== Inizia a utilizzare Workload Factory per rilevare e correggere le configurazioni errate dei workload

Per iniziare a usare Workload Factory, registrati, aggiungi le credenziali e stabilisci la connettività per gestire le risorse AWS e ottimizzare i carichi di lavoro utilizzando Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["Avvio rapido"]



== Informazioni correlate

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementare FSx ben progettato per i file system ONTAP"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare carichi di lavoro di database ben progettati"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementare configurazioni EVS ben architettate"^]

