---
sidebar: sidebar 
permalink: whats-next.html 
keywords: what you can do 
summary: 'Dopo aver effettuato l"accesso e configurato Workload Factory, è possibile creare e gestire i file system FSx for ONTAP e utilizzare altre funzionalità di Workload Factory.' 
---
= Ottimizza i carichi di lavoro con Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Dopo aver effettuato l'accesso e configurato Workload Factory, puoi iniziare a utilizzare diverse funzionalità di Workload Factory, come la creazione di file system Amazon FSx for ONTAP , la distribuzione di database su file system FSx for ONTAP e la migrazione delle configurazioni delle macchine virtuali su VMware Cloud on AWS utilizzando i file system FSx for ONTAP come datastore esterni.

* https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Amazon FSX per NetApp ONTAP"^]
+
Valuta e analizza gli ambienti dati correnti per ottenere potenziali risparmi sui costi usando FSX per ONTAP come infrastruttura storage, effettua il provisioning e Templatizza le implementazioni di FSX per ONTAP in base alle Best practice e accedi a funzioni di gestione avanzate.

* https://docs.netapp.com/us-en/workload-databases/index.html["Workload dei database"^]
+
Rileva il tuo ambiente di database esistente in AWS, valuta i potenziali risparmi sui costi passando a FSX per ONTAP, implementa database end-to-end con Best practice integrate per l'ottimizzazione e automatizza il thin cloning per pipeline ci/CD.

* https://docs.netapp.com/us-en/workload-genai/index.html["Genai"^]
+
Implementa e gestisci un'infrastruttura RAG (Retrieval-Augmented Generation) per migliorare la precisione e l'unicità delle tue applicazioni ai. Crea una knowledge base RAG su FSX per ONTAP con sicurezza e conformità dei dati integrate.

* https://docs.netapp.com/us-en/workload-vmware/index.html["Workload VMware"^]
+
Ottimizza migrazioni e operazioni con consigli smart e correzioni automatiche. Distribuire backup efficienti e un disaster recovery solido. Monitora e risolvi i problemi delle macchine virtuali.


