---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 'Scopri le novità delle funzioni di amministrazione di workload Factory: Credenziali di cloud provider, miglioramenti di Codebox e molto altro ancora.' 
---
= Novità
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità delle funzioni di amministrazione di workload Factory: Credenziali di cloud provider, miglioramenti di Codebox e molto altro ancora.



== 4 agosto 2024



=== Supporto terraforme

Il supporto per Terraform è disponibile per Amazon FSX per l'implementazione del file system NetApp ONTAP e la creazione delle VM di storage. La guida di installazione e amministrazione contiene ora le istruzioni per l'uso di Terraform dal Codebox.

link:use-codebox.html["Utilizzare Terraform da Codebox"]



== 7 luglio 2024



=== Release iniziale di workload Factory

BlueXP workload Factory per AWS è una potente piattaforma di gestione del ciclo di vita progettata per aiutarti a ottimizzare i carichi di lavoro utilizzando i file system di Amazon FSX per NetApp ONTAP. I carichi di lavoro che possono essere ottimizzati utilizzando workload Factory e FSX per ONTAP includono database, migrazioni VMware su VMware Cloud su AWS, chatbot ai e altro ancora.
